name: Build and Test

on:
  push:
    paths:
      - 'dfs/**'
      - 'bfs/**'
  pull_request:
    paths:
      - 'dfs/**'
      - 'bfs/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        algorithm: [dfs, bfs, other_algorithm]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check if directory exists
      id: check-directory
      run: if [ ! -d "${{ matrix.algorithm }}" ]; then echo "Directory does not exist"; exit 0; fi

    - name: Install dependencies
      if: steps.check-directory.outputs.exit_code != '0'
      run: sudo apt-get install -y cmake g++ python3 python3-pip

    - name: Install cpplint
      if: steps.check-directory.outputs.exit_code != '0'
      run: pip3 install cpplint

    - name: Run cpplint
      if: steps.check-directory.outputs.exit_code != '0'
      run: cpplint --recursive src test include
      working-directory: ${{ matrix.algorithm }}

    - name: Configure CMake
      if: steps.check-directory.outputs.exit_code != '0'
      run: cmake -B build -DENABLE_TESTING=ON
      working-directory: ${{ matrix.algorithm }}

    - name: Build
      if: steps.check-directory.outputs.exit_code != '0'
      run: cmake --build build
      working-directory: ${{ matrix.algorithm }}

    - name: Run tests
      if: steps.check-directory.outputs.exit_code != '0'
      run: ctest -C Release --output-on-failure
      working-directory: ${{ matrix.algorithm }}/build