name: DFS CI

on:
  push:
    paths:
      - 'dfs/**'
  pull_request:
    paths:
      - 'dfs/**'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/dfs/build -S ${{github.workspace}}/dfs -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_TESTING=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/dfs/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/dfs/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure